package lab02.hunter.group4.a1;
/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import java.util.Scanner;

import static lab02.hunter.group4.a1.User.register_admin;

public class App {
    public static int errorCheck(String input){

        int intChoice;
        try {
            intChoice = Integer.parseInt(input);
        } catch (NumberFormatException e) {
            System.out.println("Invalid option. Please select a valid option.");
            return 0;
        }
        return intChoice;
    }

    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);
        System.out.println("Welcome to the Menu App!");

        // Create an instance of User to handle user authentication
        User currentUser = null;

        while (currentUser == null) {
            System.out.println("1. Login as Admin");
            System.out.println("2. Use as General User");
            System.out.println("3. Exit");
            System.out.print("Select an option: ");
            String choice = scanner.nextLine();
            int validChoice = errorCheck(choice);

            if (validChoice == 0) {
                continue;
            }


            switch (validChoice) {
                case 1:
                    // Admin login
                    System.out.print("Enter admin username: ");
                    String adminUsername = scanner.nextLine();
                    System.out.print("Enter admin password: ");
                    String adminPassword = scanner.nextLine();

                    currentUser = User.login(adminUsername, adminPassword, JsonManagement.ADMIN_FILE);
                    if (currentUser == null) {
                        System.out.println("Login failed. Please try again.");
                    }
                    break;

                case 2:
                    // General user, no login required
                    currentUser = new User("GeneralUser", "", false);
                    break;
                case 3:
                    System.out.println("Exiting...");
                    System.exit(0);
                    return;

                default:
                    System.out.println("Invalid option. Please select a valid option.");
                    break;
            }
        }

        // Now that we have a logged-in user, we can proceed with either admin or general user functions.

        if (currentUser.getIs_admin()) {
            // Admin user
            System.out.println("Logged in as Admin.");

            while (true) {
                System.out.println("\nAdmin Functions:");
                System.out.println("1. Modify Menu");
                System.out.println("2. View Order History");
                System.out.println("3. View Menu");
                System.out.println("4. Start My Order");
                System.out.println("5. Register as Admin");
                System.out.println("6. Logout");
                System.out.print("Select an option: ");
                String choice = scanner.nextLine();
                int validChoice = errorCheck(choice);

                if (validChoice == 0) {
                    continue;
                }

                switch (validChoice) {
                    case 1:
                        // Modify Menu
                        Menu adminMenu = new Menu();
                        adminMenu.Astart(JsonManagement.MENU_FILE);
                        break;

                    case 2:
                        // View Order History
                        OrderHistory orderHistory = new OrderHistory(true, JsonManagement.ORDER_FILE);
                        orderHistory.display_order_history();
                        break;
                    case 3:
                        // View Menu
                        Menu generalMenu = new Menu();
                        generalMenu.Gstart();
                        break;
                    case 4:
                        // Start My Order
                        Cart cart = new Cart();
                        cart.Cstart();
                        break;
                    case 5:
                        // Register as Admin
                        System.out.print("Enter a new admin username: ");
                        String newAdminUsername = scanner.nextLine();
                        System.out.print("Enter a new admin password: ");
                        String newAdminPassword = scanner.nextLine();

                        // Register a new admin user
                        User registeredAdmin = register_admin(newAdminUsername, newAdminPassword, true, JsonManagement.ADMIN_FILE);
                        if (registeredAdmin != null) {
                            System.out.println("Admin registration successful.");
                        } else {
                            System.out.println("Admin registration failed.");
                        }
                        break;
                    case 6:
                        // Logout
                        User.logout();
                        break;

                    default:
                        System.out.println("Invalid option. Please select a valid option.");
                        break;
                }
            }
        } else {
            // General user
            System.out.println("Logged in as General User.");

            while (true) {
                System.out.println("\nGeneral User Functions:");
                System.out.println("1. View Menu");
                System.out.println("2. Start My Order");
                System.out.println("3. Logout");
                System.out.print("Select an option: ");
                String choice = scanner.nextLine();
                int validChoice = errorCheck(choice);
                System.out.println("\n");

                if (validChoice == 0) {
                    continue;
                }

                switch (validChoice) {
                    case 1:
                        // View Menu Categories
                        Menu generalMenu = new Menu();
                        generalMenu.Gstart();
                        break;

                    case 2:
                        // Add Items to Cart
                        Cart cart = new Cart();
                        cart.Cstart();
                        break;

                    case 3:
                        // Logout
                        User.logout();
                        break;

                    default:
                        System.out.println("Invalid option. Please select a valid option.");
                        break;
                }
            }
        }
    }
}